dist: bionic


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8


before_script: 
    - sudo apt-get update  -qq
    - sudo apt-get install libctypes-ocaml libparmap-ocaml-dev libc-dev -y
    - sudo apt install ocaml-nox -y -qq
